### PR TITLE
chore: bump version of minimatch due to security issue PRISMA-2022-0039

### PR DESCRIPTION
**Pull request by opravil-jan**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[x ] Other, please explain: fixing security issue by bump package version

### CODE REVIEW

**Review by juniorpb — APPROVED** [review]

**Comment by nzakas** [comment]
Can you please link the security bulletin so we can review?

**Comment by opravil-jan** [comment]
Hi,
here is print screen from out vulnerability management Prisma with link to code

Screenshot from 2022-04-13 09-16-06
 
https://github.com/isaacs/minimatch/commit/a8763f4388e51956be62dc6025cec1126beeb5e6

**Comment by nzakas** [comment]
Can you link to the CVE directly? The code doesn’t tell us anything.

**Comment by opravil-jan** [comment]
The link is below the picture. Here it is again:  https://github.com/isaacs/minimatch/commit/a8763f4388e51956be62dc6025cec1126beeb5e6 and also I print screen you a description in our vulnerability management.

**Comment by nzakas** [comment]
Thanks. We need to coordinate this with changes in the main repo.

Note that the vulnerability does not affect ESLint users because it’s not a server application accepting unknown inputs.

**Comment by snitin315** [comment]
I tried this PR against the latest `main` branch of eslint, all tests seem to pass - https://github.com/snitin315/eslint/pull/1

**Comment by nzakas** [comment]
Thanks! Can you try creating a draft pull request to the main repo with your work so the CI will trigger? We had failures in the main repo on the PR that makes this same upgrade directly in the eslint repo.

**Comment by mdjermanovic** [comment]
While the following usage apparently isn't covered by the test cases, and perhaps isn't something we intended to support, I've just tried it with the current ESLint v8.14.0 and it works on Windows (I'm getting `no-undef` errors in `foo\bar.js` file):

```js
module.exports = {
    overrides: [{
        files: ["foo\\bar.js"],
        rules: {
            "no-undef": "error"
        }
    }]
};
```

However, when I replace minimatch v3 with minimatch v5, it doesn't work anymore.

This seems like a risky change, so maybe we could leave it for the next major version, and in the meantime just update the dependency requirement to `"minimatch": "^3.1.2"` if that will fix the security issue?

**Comment by nzakas** [comment]
> This seems like a risky change, so maybe we could leave it for the next major version, and in the meantime just update the dependency requirement to "minimatch": "^3.1.2" if that will fix the security issue?

Agree, though I’d add let’s wait for the new config system before risking a major upgrade.

**Comment by mdjermanovic** [comment]
It seems we agree to postpone using minimatch v5.

@opravil-jan can you update this PR and https://github.com/eslint/eslint/pull/15774 to minimatch v3.1.2?

**Comment by opravil-jan** [comment]
Hi, for me it is okay. Thank you guys

**Review by mdjermanovic — APPROVED** [review]

**Pull request merged**
