### PR TITLE
ci: run tests on Node.js v20

### PR DESCRIPTION
**Pull request by snitin315**
#### What changes did you make? (Give an overview)

- run tests on Node.js v20
- ~Remove Node v19 and v17 from matrix~

### CODE REVIEW

**Comment by ljharb** [comment]
node 19 isn’t eol yet and should be kept, since dropping a platform is a breaking change. Probably node 17 applies too.

**Comment by snitin315** [comment]
Yeah. I'll keep b17 and v19. Although support wasn't dropped, only tests on CI. But let's keep it.

**Comment by ljharb** [comment]
If it’s not tested then it’s not supported.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
